version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          command: |
            sudo pip install -e .
            pytest


