version: 2.0

jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
      - run:
          command: |
            pytest


